version: '2.2'

services:
  web:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: httpd.access

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - fluentbit
   
        
  # Elasticsearch requires your vm.max_map_count set to 262144
  # Default will be 65530
  # sysctl -w vm.max_map_count=262144
  # Add this to /etc/sysctl.conf for making it permanent
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
  # command: ["sysctl", "-w", "vm.max_map_count=262144"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibanaa:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibanaa
    environment:
      ELASTICSEARCH_URL: "http://localhost:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      
  fluentbit:
    build: ./fluentbit
    container_name: fluentbit
    volumes:
      - ./fluentbit/conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    ports:
        - 2020:2020
        - 2020:2020/udp
    depends_on:
      - elasticsearch
      - kibanaa
      

volumes:
  esdata1:
    driver: local

#networks:
 # global:
      
